"""departments, programs, courses, users

Revision ID: e1ac2494d08d
Revises: 
Create Date: 2019-03-19 22:17:38.578141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ac2494d08d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('prereq_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['prereq_id'], ['courses.id'], )
    )
    # ### end Alembic commands ###
